x-airflow-common: &airflow-common
  build:
      context: ./airflow
  #image: apache/airflow:2.9.1-python3.11
  env_file:
    - .env
  environment: 
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:  postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${AIRFLOW_DB}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW_FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
    AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: '1'    # Évite la surcharge simultanée
    AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: '4'   # Limite le parallélisme par DAG
    AIRFLOW__CORE__DAGBAG_IMPORT_TIMEOUT: '120'    # DAGs lourds = plus de temps de parse
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_PRE_PING: 'true'   # ← détecte les connexions mortes
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_RECYCLE: 1800
    AIRFLOW__DATABASE__SQL_ALCHEMY_POOL_SIZE: 5
    
    # Connexions Minio / S3
    AIRFLOW_CONN_MINIO_DEFAULT: s3://${DATALAKE_USER}:${DATALAKE_PASSWORD}@minio:9000

    # Spark
    SPARK_MASTER_URL: spark://spark-master:7077

    # MinIO
    MINIO_ENDPOINT: http://minio:9000
    MINIO_ACCESS_KEY: ${DATALAKE_USER}
    MINIO_SECRET_KEY: ${DATALAKE_PASSWORD}
    OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    POSTGRES_CONN: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    # PySpark / Java
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
    SPARK_HOME: /opt/spark
    PYTHONPATH: /opt/airflow/dags:/opt/airflow/scripts
    AIRFLOW__WEBSERVER__WORKERS: '2'               # Gunicorn : 2 workers suffisent
    AIRFLOW__WEBSERVER__WORKER_TIMEOUT: '120'
    AIRFLOW__WEBSERVER__WORKER_REFRESH_BATCH_SIZE: '1'

  volumes:
    - spark_home:/opt/spark 
  depends_on:
    postgres:
      condition: service_healthy

  networks:
    - data-net


services:
  # ─────────────────────────────────────────────
  #  DATALAKE (minio)
  # ─────────────────────────────────────────────
  minio:
    image: minio/minio
    container_name: minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${DATALAKE_USER}
      MINIO_ROOT_PASSWORD: ${DATALAKE_PASSWORD}
    ports:
      - "9000:9000"   # API S3
      - "9001:9001"   # Console Web
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 15s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
    networks:
      - data-net

  # Initialise les buckets Minio au démarrage
  minio-init:
    image: minio/mc
    container_name: minio_init
    env_file:
      - .env
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      mc alias set local http://minio:9000 $${DATALAKE_USER} $${DATALAKE_PASSWORD};
      mc mb --ignore-existing local/raw-taxi;
      mc mb --ignore-existing local/raw-weather;
      mc mb --ignore-existing local/raw-weather-faker;
      mc mb --ignore-existing local/processed;
      echo 'Buckets créés avec succès';
      exit 0;
      "
    networks:
      - data-net

  # ─────────────────────────────────────────────
  #  DWH BDD SQL
  # ─────────────────────────────────────────────
  postgres:
    image: postgres:15
    container_name: postgres_dwh
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB} # Ajouter db sur l'analytic pour dbt
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      retries: 5
      start_period: 30s
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d  # scripts SQL d'init (multi-DB)
    networks:
      - data-net
      
  # ─────────────────────────────────────────────
  #  Marimo analytique
  # ─────────────────────────────────────────────
  marimo:
    build:
      context: ./marimo-analytics
    env_file:
      - .env
    container_name: marimo-analytics
    command: marimo edit --no-token --host 0.0.0.0 -p 8080
    working_dir: /code
    ports:
      - "${MARIMO_ANALYTICS_PORT}:8080"
    stdin_open: true
    tty: true
    networks:
      - data-net


  # Service dbt (conteneur gardé allumé exprès pour lancer les différents modèles dbt)
  dbt:
    build:
      context: ./dbt
    env_file:
      - .env
    working_dir: /dbt
    environment:
      DBT_PROFILES_DIR: /dbt/analytics
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # Conteneur gardé ouvert pour lancer les commandes manuellement
    entrypoint: ["tail", "-f", "/dev/null"]
    depends_on:
      postgres:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - data-net

  # Service airflow (Pyspark et Pyspark Streaming qui doit être installée et configuré)
  # ─────────────────────────────────────────────
  #  AIRFLOW
  # ─────────────────────────────────────────────

  airflow-init:
    <<: *airflow-common
    container_name: airflow_init
    entrypoint: /bin/bash
    command:
      - -c
      - | 
        airflow db migrate
        airflow users create \
          --username ${AIRFLOW_ADMIN_USER:-admin} \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email ${AIRFLOW_ADMIN_EMAIL:-admin@local.dev} \
          --password ${AIRFLOW_ADMIN_PASSWORD:-admin} || true
    environment:
      <<: *airflow-common-env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - data-net

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow_webserver
    command: airflow webserver
    ports:
      - "8082:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    environment:
      <<: *airflow-common-env
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - data-net

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow_scheduler
    command: airflow scheduler
    environment:
      <<: *airflow-common-env
    healthcheck:
      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --hostname $(hostname)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    networks:
      - data-net

  # ─────────────────────────────────────────────
  #  SPARK (pour l'exécution des jobs spark sous AIRFLOW)
  # ─────────────────────────────────────────────
  spark-master:
    build:
      context: ./spark
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_NO_DAEMONIZE=true
    volumes:
      - spark_home:/opt/spark  
    ports:
      - "7077:7077"   # cluster endpoint (IMPORTANT pour Airflow)
      - "8084:8080"   # UI Spark
    networks:
      - data-net

  spark-worker:
    build:
      context: ./spark
    container_name: spark-worker-1
    depends_on:
      - spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    environment:
      - SPARK_NO_DAEMONIZE=true
    ports:
      - "8081:8081"
    networks:
      - data-net

# ─────────────────────────────────────────────
#  VOLUMES (persistance locale + Docker volumes)
# ─────────────────────────────────────────────

volumes:
  spark_home:
  postgres_data:
  minio_data:

# ─────────────────────────────────────────────
#  RÉSEAU INTERNE
# ─────────────────────────────────────────────

networks:
  data-net:
    driver: bridge
