analytics:

  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: POSTGRES123
      port: 5434
      dbname: data_warehouse
      schema: mart
      threads: 1

  target: dev